### ISSUE TITLE
[Suggestion] Design rework

### ISSUE THREAD

**Issue by Priyanshu-Prime** [amandollar/BAASSKY-#3]
The search bar takes away the focus from the name of the page due to being on top of it. Can we move the search bar on the top right in the nav bar and move the nav bar options to the left after the logo? 

![Screenshot 2024-07-05 023720](https://github.com/amandollar/BAASSKY-/assets/129518661/34ffcc8d-81fb-4151-84d4-7e64d89d16a4)

**Comment by amandollar** [comment]
Sure
